/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/grass.glb 
Author: Digital screen official (https://sketchfab.com/ck212575)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grass-02-539d1c154c944e24a04478ee32f0a960
Title: Grass 02
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/grass.glb')

  // Clone material and set transparency
  const transparentMaterial = materials.Material.clone()
  transparentMaterial.transparent = true
  transparentMaterial.opacity = 0.35

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={transparentMaterial} rotation={[-Math.PI / 2, 0, 0]} castShadow receiveShadow />
    </group>
  )
}

useGLTF.preload('/grass.glb')
