/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/spear.glb 
Author: Sir Erdees (https://sketchfab.com/sirerdees)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-spear-2-0289b47254b7410e985f1f2e8651323a
Title: Stylized Spear 2
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/spear.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.02}>
        <mesh geometry={nodes.wooden_low_spear_1_txtr_0.geometry} material={materials.spear_1_txtr} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.blade_low_spear_1_txtr_0.geometry} material={materials.spear_1_txtr} position={[0, 0, 3.846]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.hand_low_spear_1_txtr_0.geometry} material={materials.spear_1_txtr} position={[0, 0, 8.575]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.pimp_low_spear_1_txtr_0.geometry} material={materials.spear_1_txtr} position={[0, 0, -170.62]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/spear.glb')
