/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/tree.glb 
Author: evolveduk (https://sketchfab.com/evolveduk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/acacia-tree-bb14c2bb679b4d0bb1c578a27e2ddabf
Title: Acacia tree
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tree.glb')

  // Clone materials and add transparency
  const transparentBarkMaterial = materials.bark05_0Mat.clone()
  transparentBarkMaterial.transparent = true
  transparentBarkMaterial.opacity = 1

  const transparentBranchMaterial = materials.acacia_branch_1Mat.clone()
  transparentBranchMaterial.transparent = true
  transparentBranchMaterial.opacity = 1

  return (
    <group {...props} dispose={null}>
      <group scale={0.0075}>
        <mesh geometry={nodes.bark05_0_bark05_0Mat_0.geometry} material={transparentBarkMaterial} />
        <mesh geometry={nodes.acacia_branch_1_acacia_branch_1Mat_0.geometry} material={transparentBranchMaterial} />
      </group>
    </group>
  )
}

useGLTF.preload('/tree.glb')
